spring:
  application:
    name: User-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/usercenter
  session:
    timeout: 86400
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB     #单个文件最大限制
      max-request-size: 50MB  #多个文件最大限制
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
aliyun:
  oss:
    end-point: # OSS服务的访问域名，例如：oss-cn-hangzhou.aliyuncs.com
    access-key-id: # 阿里云账号的访问密钥ID，用于身份验证
    access-key-secret: # 阿里云账号的访问密钥Secret，用于身份验证
    bucket-name: # OSS存储空间的名称，存放文件的容器